version: "3.6"

services:
  postgres:    
    build: 
      context: ./
    container_name: postgres-data-echo
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - data-echo-network
    ports:
      - 5432:5432

networks:
  data-echo-network:
    external: true
