version: "3.4"

## x-datanode_base서비스를 변수 &datanode_base에 담기, 호출 *datanode_base
## 공통적인 부분 image명과 network명. 허나 개별서비스내 항목이 있으면 덮어쓰기됨.
x-datanode_base: &datanode_base
  image: hadoop-datanode
  networks:
    # - bridge
    - data-echo-network

services:
  namenode:
    image: hadoop-namenode
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"
      - "9000:9000"
      - "9870:9870"
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - /tmp:/tmp
    networks:
      # - bridge
      - data-echo-network

  datanode01:
    <<: *datanode_base
    container_name: datanode01
    hostname: datanode01
    volumes:
      - datanode01:/opt/hadoop/dfs/data

  datanode02:
    <<: *datanode_base
    container_name: datanode02
    hostname: datanode02
    volumes:
      - datanode02:/opt/hadoop/dfs/data

volumes:
  namenode:
  datanode01:
  datanode02:

networks:
  # bridge:
  data-echo-network:
    external: true