version: '3.7'

services:
  hadoop:
    build: .
    container_name: hadoop
    volumes:
      - ./data/name:/opt/hadoop/dfs/name
      - ./data/data:/opt/hadoop/dfs/data
    ports:
      - "9000:9000"
      - "9870:9870"
    networks:
      - data-echo-network
networks:
  data-echo-network:
    external: true