Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.box_version = "4.2.16"
    config.vm.network "forwarded_port", host: 9000, guest: 9000, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", host: 9870, guest: 9870, host_ip: "127.0.0.1"
    config.vm.network "private_network", ip: "192.168.33.11"
    # 마운트 시킬 호스트의 상위폴더는 미리 생성 해야한다
    config.vm.synced_folder "../../hdfs01_hd02_folder", "/sync"
    config.vm.post_up_message
    config.vm.provider "virtualbox" do |machine|
        machine.memory=4096
        machine.cpus=4
        machine.name="ubuntu_2204"
        machine.check_guest_additions=false
        # 호스트리소스 최대사용 허용치 설정(단위%)
        machine.customize ["modifyvm", :id, "--vram", "128", "--cpuexecutioncap", "50"]
    end
    ### 도커관련
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update -q
        wget -qO- https://get.docker.com/ | sh
        sudo snap install docker
        usermod -aG docker vagrant
    SHELL
    ### 기타
    config.vm.provision "shell", inline: <<-SHELL
        sudo cp -r /sync/* /
        # docker compose -f /hadoop/docker-compose.yml up -d --build
        # docker compose -f /hue/docker-compose.yml up -d --build
    SHELL
    # config.vm.provision "shell", inline: "docker compose -f /hadoop/docker-compose.yml up -d --build"
  end