# -*- mode: ruby -*-
# vi: set ft=ruby :
# reference site https://jaynamm.tistory.com/entry/11-VagrantFile-%EC%83%9D%EC%84%B1-%EB%B0%8F-3%EA%B0%9C%EC%9D%98-%EA%B0%80%EC%83%81-%EB%A8%B8%EC%8B%A0-%EC%83%9D%EC%84%B1
Vagrant.configure("2") do |config|
  ### Master Node ####
  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2204"
    master.vm.box_version = "4.2.16"
    master.vm.provider "virtualbox" do |machine|
      machine.name = "master"
      machine.cpus = 2
      machine.memory = 3072
      machine.customize ["modifyvm", :id, "--groups", "/cluster"]
    end
    master.vm.host_name = "master"
    master.vm.network "private_network", ip: "192.168.1.10"
    master.vm.network "forwarded_port", guest: 22, host: 10030, auto_correct: true, id: "ssh"
    master.vm.synced_folder ".", "/vagrant", disabled: true
  end
  
  ### Worker node ###
  (1..2).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.box_version = "4.2.16"
      worker.vm.provider "virtualbox" do |machine|
        machine.name = "worker#{i}"
        machine.cpus = 1
        machine.memory = 2048
        machine.customize ["modifyvm", :id, "--groups", "/cluster"]
      end
      worker.vm.host_name = "worker#{i}"
      worker.vm.network "private_network", ip: "192.168.1.1#{i}"
      worker.vm.network "forwarded_port", guest: 22, host: "1003#{i}", auto_correct: true, id: "ssh"
      worker.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end

end