Vagrant.configure("2") do |config|
    # config.vm.box = "ubuntu/bionic64"
    # config.vm.box_version = "20210508.0.0"
    config.vm.box = "generic/ubuntu2204"
    config.vm.box_version = "4.2.16"
    config.vm.network "forwarded_port", guest: 1333, host: 1333, host_ip: "127.0.0.1"
    config.vm.network "private_network", ip: "192.168.33.11"
    # 마운트 시킬 호스트의 상위폴더는 미리 생성 해야한다
    config.vm.synced_folder "../../hdfs01_sync_folder", "/sync"
    config.vm.post_up_message
    config.vm.provider "virtualbox" do |machine|
        machine.memory=4096
        machine.cpus=4
        machine.name="ubuntu_2204"
        machine.check_guest_additions=false
        # 호스트리소스 최대사용 허용치 설정(단위%)
        machine.customize ["modifyvm", :id, "--vram", "128", "--cpuexecutioncap", "50"]
    end

    ### 도커관련
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update -q
        wget -qO- https://get.docker.com/ | sh
        usermod -aG docker vagrant
    SHELL

    # 각종 서비스, 라이브러리 설치
    config.vm.provision "shell", path: "requirements.sh"

    # 설치후 작업
    config.vm.provision "hdfs", type: "shell", inline: <<-SHELL
        # sudo chown YOURUSER:YOURUSER -R /home/YOURUSER/hadoop/*
        # sudo chmod -R 777 /usr/local/Cellar/hadoop/hdfs/tmp
        HDFS_ETC=/hadoop-3.3.4/etc/hadoop/
        sudo cp /sync/core-site.xml $HDFS_ETC
        sudo cp /sync/hadoop-env.sh $HDFS_ETC
        sudo cp /sync/hdfs-site.xml $HDFS_ETC
    SHELL

    # 'never'의 실행법: vagrant provision --provision-with test
    config.vm.provision "test", type: "shell", run: "never" do |mytest|
        mytest.inline = "echo hello"
    end
  end